# Generated by Django 5.1 on 2024-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_name', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('thana', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
