# Generated by Django 5.1 on 2024-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosque',
            old_name='staff_mobile_number',
            new_name='imam_mobile_number',
        ),
        migrations.RenameField(
            model_name='mosque',
            old_name='staff_name',
            new_name='imam_name',
        ),
        migrations.AddField(
            model_name='mosque',
            name='muazzin_mobile_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='muazzin_name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
