# Generated by Django 5.1 on 2024-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_mosque_imam_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='district',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosque',
            name='division',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='thana',
            field=models.CharField(max_length=255),
        ),
    ]
