# Generated by Django 5.1 on 2024-08-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_bank_mobilebank_qarrj_hasana'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qarrj_Hasana',
            new_name='Qarrj_Hasana_Accounts',
        ),
    ]
