# Generated by Django 5.1 on 2024-08-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_qarrj_hasana_qarrj_hasana_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qarrj_Hasana_Accounts',
            new_name='Qarrj_Hasana_Account',
        ),
    ]
