# Generated by Django 5.1 on 2024-08-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_rename_qarrj_hasana_accounts_qarrj_hasana_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarrj_hasana_account',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Qarrj_Hasana_Apply',
            fields=[
                ('form_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('head_of_family_name', models.CharField(max_length=255)),
                ('total_members_boy', models.PositiveIntegerField(default=0)),
                ('total_members_girl', models.PositiveIntegerField(default=0)),
                ('total_workable_persons', models.PositiveIntegerField(default=0)),
                ('total_earnable_persons', models.PositiveIntegerField(default=0)),
                ('source_of_income', models.CharField(max_length=255)),
                ('total_monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_monthly_expence', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_savings_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_installment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_unpaid_installment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('have_bangla_translated_if_quran', models.BooleanField(default=False)),
                ('recite_quran_daily', models.BooleanField(default=False)),
                ('income_expense_diff_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('qarrj_hasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registration.qarrj_hasana_account')),
            ],
        ),
    ]
