# Generated by Django 5.1 on 2024-08-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_qarrj_hasana_account_email_qarrj_hasana_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='form_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
