# Generated by Django 5.1 on 2024-08-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_qarrj_hasana_apply_form_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='requested_qarrj_hasana_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
