# Generated by Django 5.1 on 2024-08-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_qarrj_hasana_apply_requested_qarrj_hasana_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarrj_hasana_apply',
            old_name='requested_qarrj_hasana_amount',
            new_name='requested_amount_for_qarrj_hasana',
        ),
        migrations.RenameField(
            model_name='qarrj_hasana_apply',
            old_name='total_monthly_expence',
            new_name='total_monthly_expense',
        ),
    ]
