# Generated by Django 5.1 on 2024-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_rename_requested_qarrj_hasana_amount_qarrj_hasana_apply_requested_amount_for_qarrj_hasana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='monthly_savings_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
