# Generated by Django 5.1 on 2024-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_qarrj_hasana_apply_monthly_savings_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='income_expense_diff_amount',
            field=models.DecimalField(decimal_places=0, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='loan_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='monthly_installment_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_monthly_expense',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_monthly_income',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_unpaid_installment_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
