# Generated by Django 5.1 on 2024-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_qarrj_hasana_apply_income_expense_diff_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_monthly_expense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_monthly_income',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
