# Generated by Django 5.1 on 2024-08-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_qarrj_hasana_apply_total_monthly_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakat_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Zakat_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.mosque')),
            ],
        ),
    ]
