# Generated by Django 5.1 on 2024-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_zakat_wallet_zakat_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakat_provider',
            name='donation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
