# Generated by Django 5.1 on 2024-08-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_zakat_provider_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakat_wallet',
            name='mosque',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='registration.mosque'),
            preserve_default=False,
        ),
    ]
