# Generated by Django 5.1 on 2024-08-31 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_zakat_wallet_mosque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='zakat_wallet',
            name='service_charge_percentage',
        ),
    ]
