# Generated by Django 5.1 on 2024-09-01 04:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_global_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakat_Receiver',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('nid_no', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_bank_number', models.CharField(blank=True, max_length=15, null=True)),
                ('form_no', models.AutoField(primary_key=True, serialize=False)),
                ('head_of_family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_members_boy', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_members_girl', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_workable_persons', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_earnable_persons', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('source_of_income', models.CharField(blank=True, max_length=255, null=True)),
                ('total_monthly_income', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_monthly_expense', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('monthly_savings_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('monthly_installment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('total_unpaid_installment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('have_bangla_translated_if_quran', models.BooleanField(default=False)),
                ('recite_quran_daily', models.BooleanField(default=False)),
                ('income_expense_diff_amount', models.DecimalField(blank=True, decimal_places=0, default=0.0, editable=False, max_digits=15, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.bank')),
                ('mobile_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mobilebank')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Zakat_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.zakat_receiver')),
            ],
        ),
    ]
