# Generated by Django 5.1 on 2024-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_remove_personal_zakat_wallet_amount_mosque_mosque_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='mosque_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
