# Generated by Django 5.1 on 2024-09-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_mosque_mosque_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarrj_hasana_account',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_account',
            name='nid_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
