# Generated by Django 5.1 on 2024-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_qarrj_hasana_account_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakat_receiver',
            name='note',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
