# Generated by Django 5.1 on 2024-09-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_zakat_receiver_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakat_receiver',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
