# Generated by Django 4.1.5 on 2024-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_alter_zakat_receiver_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smf_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
