# Generated by Django 4.1.5 on 2024-10-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_homepagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='banner_image1',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='banner_image2',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='banner_image3',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='banner_image4',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='banner_image5',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
