# Generated by Django 4.1.5 on 2024-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_homepagemodel_banner_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image1', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('banner_image2', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('banner_image3', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('banner_image4', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('banner_image5', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepagemodel',
            name='banner_image1',
        ),
        migrations.RemoveField(
            model_name='homepagemodel',
            name='banner_image2',
        ),
        migrations.RemoveField(
            model_name='homepagemodel',
            name='banner_image3',
        ),
        migrations.RemoveField(
            model_name='homepagemodel',
            name='banner_image4',
        ),
        migrations.RemoveField(
            model_name='homepagemodel',
            name='banner_image5',
        ),
    ]
