# Generated by Django 4.1.5 on 2024-10-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_bannermodel_remove_homepagemodel_banner_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='banner_image1',
            new_name='banner_image',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='banner_image2',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='banner_image3',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='banner_image4',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='banner_image5',
        ),
    ]
