# Generated by Django 5.1 on 2024-10-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_rename_banner_image1_bannermodel_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='village',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
