# Generated by Django 5.1 on 2024-10-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_alter_zakat_wallet_mosque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qarrj_hasana_account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='qarrj_hasana_account',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='qarrj_hasana_account',
            name='mobile_bank',
        ),
        migrations.RemoveField(
            model_name='qarrj_hasana_account',
            name='mobile_bank_number',
        ),
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.bank'),
        ),
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='mobile_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.mobilebank'),
        ),
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='mobile_bank_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
