# Generated by Django 5.1 on 2024-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_alter_qarrj_hasana_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_primary', models.CharField(max_length=15)),
                ('phone_number_secondery', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='income_expense_diff_amount',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='requested_amount_for_qarrj_hasana',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_earnable_persons',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_members_boy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_members_girl',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_monthly_expense',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_monthly_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='total_workable_persons',
            field=models.PositiveIntegerField(),
        ),
    ]
