# Generated by Django 5.1 on 2024-10-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_admininformation_qarrj_hasana_apply_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
