# Generated by Django 5.1 on 2024-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_qarrj_hasana_apply_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('close', 'close')], default='pending', max_length=10),
        ),
    ]
