# Generated by Django 5.1 on 2024-10-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_alter_qarrj_hasana_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarrj_hasana_apply',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_screenshots/'),
        ),
    ]
