# Generated by Django 5.1 on 2024-10-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_qarrj_hasana_apply_transaction_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformation',
            name='phone_number_primary',
            field=models.CharField(max_length=20),
        ),
    ]
