# Generated by Django 5.1 on 2024-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_alter_admininformation_phone_number_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakat_provider',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='zakat_provider_trs_ss/'),
        ),
        migrations.AlterField(
            model_name='qarrj_hasana_apply',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='qarrj_transaction_screenshots/'),
        ),
    ]
