# Generated by Django 5.1 on 2024-10-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_global_settings_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global_settings',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='global_settings',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='global_settings',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='global_settings',
            name='swift_code',
        ),
    ]
