# Generated by Django 5.1 on 2024-10-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_bankinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankinfo',
            options={'verbose_name': 'Bank Info', 'verbose_name_plural': 'Bank Info'},
        ),
    ]
