# Generated by Django 5.1 on 2024-10-17 20:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_alter_bankinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_zakat_wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
