# Generated by Django 5.1 on 2024-10-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_personal_zakat_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_zakat_wallet',
            name='amount',
        ),
    ]
