# Generated by Django 5.1 on 2024-10-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_remove_personal_zakat_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakat_wallet',
            name='mosque',
        ),
        migrations.DeleteModel(
            name='Personal_Zakat_Wallet',
        ),
        migrations.DeleteModel(
            name='Zakat_Wallet',
        ),
    ]
