# Generated by Django 5.1 on 2024-10-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_remove_zakat_wallet_mosque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCardBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image_card_blogs/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
