# Generated by Django 5.1 on 2024-10-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_imagecardblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_DOB', models.DateField()),
                ('emp_designation', models.CharField(max_length=50)),
                ('emp_DOJ', models.DateField()),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phone', models.CharField(blank=True, max_length=15)),
                ('emp_address', models.TextField(blank=True)),
                ('emp_pin', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
