# Generated by Django 5.1 on 2024-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0050_employeeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_pin',
            field=models.CharField(max_length=4),
        ),
    ]
