# Generated by Django 5.1 on 2024-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_alter_employeeinfo_emp_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About SME', max_length=255)),
                ('description', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('vision_description', models.TextField()),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_description', models.TextField()),
            ],
        ),
    ]
