# Generated by Django 5.1 on 2024-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_teammemberblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='photo',
            field=models.ImageField(default=2, upload_to='emp_photo/'),
            preserve_default=False,
        ),
    ]
