# Generated by Django 5.1 on 2024-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_employeeinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=100)),
                ('attd_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_pin',
            field=models.CharField(editable=False, max_length=4),
        ),
    ]
