# Generated by Django 5.1 on 2024-10-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_alter_attendance_attd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attd_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
