# Generated by Django 5.1 on 2024-10-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_rename_attd_date_attendance__attd_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='_attd_date',
            new_name='attd_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='_in_time',
            new_name='in_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='_out_time',
            new_name='out_time',
        ),
    ]
