# Generated by Django 5.1 on 2024-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_rename__attd_date_attendance_attd_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attd_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
